# just for example run purposes

# Initialize kernel
/run/initialize

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

# E0 of background distribution out of {100,200,300} keV
/particleSource/setFoldingEnergy 300. # [keV]

# 0 = 90 deg, 1 = sin, 2 = sin^2, 3 = triangle
/particleSource/setPitchAngleDistribution 1

# run 500 for visualization
/run/beamOn 500

# to run: 
# /control/execute macros/run_example.mac