/run/numberOfThreads 14 
/run/initialize 
/control/verbose 0 
/run/verbose 0 
/event/verbose 0 
/tracking/verbose 0 
/gps/particle e- 
/gps/pos/type Plane 
/gps/pos/shape Square 
/gps/pos/halfx 5.054 cm 
/gps/pos/halfy 5.054 cm 
/gps/pos/centre 0 0 496.28 cm 
/gps/ang/type iso 
/gps/ang/rot1 -1 0 0 
/gps/ang/rot2 0 1 0 
/gps/ang/mintheta 0 deg 
/gps/ang/maxtheta 46 deg 
/gps/ene/type Mono 
/gps/ene/mono 500.0000 keV 
/run/printProgress 1692827734 
/run/beamOn 16928277345 
