# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfWorkers 4
#
# Initialize kernel
/run/initialize

/run/setCut 0.05 mm

/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0


# General Particle Source:
/gps/particle e-
/gps/position 0 -5 0 cm
/gps/pos/type Point
/gps/direction 0 1 0
/gps/energy 7000 keV

/run/beamOn 1
